### ISSUE TITLE
今天早上失效

### ISSUE THREAD

**Issue by tangli159** [harepo/hello_miai#1]
你好，今天早上我发现之前更新了的这个插件又失效了，望大大看看，及时修复 ，谢谢
错误代码1：Logger: custom_components.hello_miai
Source: custom_components/hello_miai/__init__.py:209
Integration: 小米网络tts (documentation)
First occurred: 上午11:29:56 (1 occurrences)
Last logged: 上午11:29:56

HTTPSConnectionPool(host='api2.mina.mi.com', port=443): Read timed out. (read timeout=3)、
错误代码2：
Logger: custom_components.hello_miai
Source: custom_components/hello_miai/__init__.py:110
Integration: 小米网络tts (documentation)
First occurred: 上午11:29:56 (1 occurrences)
Last logged: 上午11:29:56

login miai Failed
错误代码3：
Logger: custom_components.hello_miai
Source: custom_components/hello_miai/__init__.py:400
Integration: 小米网络tts (documentation)
First occurred: 上午11:32:26 (1 occurrences)
Last logged: 上午11:32:26

还未登录

**Comment by redyuan43** [comment]
这个方法早晚会失效的
